[project]
name = "05-deployment"
version = "0.1.0"
description = "Homework 5 for ML Zoomcamp 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.0",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
